swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /tipo_metadato_pregunta/:
    get:
      tags:
      - tipo_metadato_pregunta
      description: get TipoMetadatoPregunta
      operationId: TipoMetadatoPreguntaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoMetadatoPregunta'
        "403":
          description: ""
    post:
      tags:
      - tipo_metadato_pregunta
      description: create TipoMetadatoPregunta
      operationId: TipoMetadatoPreguntaController.Post
      parameters:
      - in: body
        name: body
        description: body for TipoMetadatoPregunta content
        required: true
        schema:
          $ref: '#/definitions/models.TipoMetadatoPregunta'
      responses:
        "201":
          description: '{int} models.TipoMetadatoPregunta'
        "403":
          description: body is empty
  /tipo_metadato_pregunta/{id}:
    get:
      tags:
      - tipo_metadato_pregunta
      description: get TipoMetadatoPregunta by id
      operationId: TipoMetadatoPreguntaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoMetadatoPregunta'
        "403":
          description: :id is empty
    put:
      tags:
      - tipo_metadato_pregunta
      description: update the TipoMetadatoPregunta
      operationId: TipoMetadatoPreguntaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for TipoMetadatoPregunta content
        required: true
        schema:
          $ref: '#/definitions/models.TipoMetadatoPregunta'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoMetadatoPregunta'
        "403":
          description: :id is not int
    delete:
      tags:
      - tipo_metadato_pregunta
      description: delete the TipoMetadatoPregunta
      operationId: TipoMetadatoPreguntaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /valor_metadato/:
    get:
      tags:
      - valor_metadato
      description: get ValorMetadato
      operationId: ValorMetadatoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ValorMetadato'
        "403":
          description: ""
    post:
      tags:
      - valor_metadato
      description: create ValorMetadato
      operationId: ValorMetadatoController.Post
      parameters:
      - in: body
        name: body
        description: body for ValorMetadato content
        required: true
        schema:
          $ref: '#/definitions/models.ValorMetadato'
      responses:
        "201":
          description: '{int} models.ValorMetadato'
        "403":
          description: body is empty
  /valor_metadato/{id}:
    get:
      tags:
      - valor_metadato
      description: get ValorMetadato by id
      operationId: ValorMetadatoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ValorMetadato'
        "403":
          description: :id is empty
    put:
      tags:
      - valor_metadato
      description: update the ValorMetadato
      operationId: ValorMetadatoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for ValorMetadato content
        required: true
        schema:
          $ref: '#/definitions/models.ValorMetadato'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ValorMetadato'
        "403":
          description: :id is not int
    delete:
      tags:
      - valor_metadato
      description: delete the ValorMetadato
      operationId: ValorMetadatoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.TipoMetadatoPregunta:
    title: TipoMetadatoPregunta
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbrevicion:
        type: string
      Descripcion:
        type: string
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      FormDefinition:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.ValorMetadato:
    title: ValorMetadato
    type: object
    properties:
      Activo:
        type: boolean
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      PersonaId:
        type: integer
        format: int64
      TipoMetadatoPreguntaId:
        $ref: '#/definitions/models.TipoMetadatoPregunta'
      Valor:
        type: string
tags:
- name: tipo_metadato_pregunta
  description: |
    TipoMetadatoPreguntaController operations for TipoMetadatoPregunta
- name: valor_metadato
  description: |
    ValorMetadatoController operations for ValorMetadato
